# Generated by Django 5.2.4 on 2025-07-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('clothing_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('thickness', models.CharField(blank=True, max_length=255, null=True)),
                ('sensitivity', models.CharField(blank=True, max_length=255, null=True)),
                ('structure', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('social_id', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_temp', models.IntegerField(blank=True, null=True)),
                ('wash_strength', models.CharField(blank=True, max_length=255, null=True)),
                ('rinse_count', models.IntegerField(blank=True, null=True)),
                ('spin_level', models.CharField(blank=True, max_length=255, null=True)),
                ('prewash', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaundrySymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='Stain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.clothing')),
            ],
        ),
        migrations.AddField(
            model_name='clothing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.user'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.clothing')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.laundrysymbol')),
                ('stain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.stain')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.washingcourse')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry_manager.washingmode')),
            ],
        ),
    ]
