# Generated by Django 5.2.4 on 2025-08-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_manager', '0002_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaundryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.CharField(help_text='입력받은 소재 정보 (쉼표로 구분)', max_length=255)),
                ('symbols', models.TextField(help_text='인식/입력된 세탁기호 목록 (쉼표로 구분)')),
                ('stains', models.CharField(blank=True, help_text='입력받은 얼룩 정보 (쉼표로 구분)', max_length=255)),
                ('recommendation_result', models.TextField(help_text='사용자에게 보여준 최종 추천 세탁법 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
