# Generated by Django 5.2.5 on 2025-08-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_manager', '0003_alter_clothing_user_laundryhistory_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('inquiry_type', models.CharField(choices=[('서비스 이용 문의', '서비스 이용 문의'), ('버그/오류 제보', '버그/오류 제보'), ('세탁소 제휴 문의', '세탁소 제휴 문의'), ('기타', '기타')], max_length=50, verbose_name='문의 유형')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('privacy_agree', models.BooleanField(default=False, verbose_name='개인정보 수집 동의')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='답변 완료 여부')),
            ],
        ),
    ]
