# Generated by Django 5.2.4 on 2025-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_manager', '0004_favoriteitem'),
        ('laundry_manager', '0004_inquiry'),
    ]

    operations = [
    ]
