# Generated by Django 5.2.4 on 2025-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_manager', '0005_merge_0004_favoriteitem_0004_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='laundryhistory',
            name='snapshot_html',
            field=models.TextField(blank=True),
        ),
    ]
